name: 'dbt_snowflake_monitoring'
version: '1.4.1'
config-version: 2

profile: dbt_snowflake_monitoring

model-paths: ["models"]

models:
  dbt_snowflake_monitoring:
    +schema: snowflake_monitoring

clean-targets:
  - target
  - dbt_packages
